version: '3'

services:
  hey-ptt:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hey-ptt
    ports:
      - '7777:7777'
    environment:
      - PORT=7777
      - HOST=0.0.0.0
    restart: unless-stopped
